// source: pb/graphsearchrpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.graphsearch.GraphSearchReply', null, global);
goog.exportSymbol('proto.graphsearch.GraphSearchRequest', null, global);
goog.exportSymbol('proto.graphsearch.OutputOracleReply', null, global);
goog.exportSymbol('proto.graphsearch.OutputOracleRequest', null, global);
goog.exportSymbol('proto.graphsearch.StatusReply', null, global);
goog.exportSymbol('proto.graphsearch.StatusRequest', null, global);
goog.exportSymbol('proto.graphsearch.TrustedValidationBulkReply', null, global);
goog.exportSymbol('proto.graphsearch.TrustedValidationBulkRequest', null, global);
goog.exportSymbol('proto.graphsearch.TrustedValidationReply', null, global);
goog.exportSymbol('proto.graphsearch.TrustedValidationRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.GraphSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.graphsearch.GraphSearchRequest.repeatedFields_, null);
};
goog.inherits(proto.graphsearch.GraphSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.GraphSearchRequest.displayName = 'proto.graphsearch.GraphSearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.GraphSearchReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.graphsearch.GraphSearchReply.repeatedFields_, null);
};
goog.inherits(proto.graphsearch.GraphSearchReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.GraphSearchReply.displayName = 'proto.graphsearch.GraphSearchReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.TrustedValidationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.graphsearch.TrustedValidationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.TrustedValidationRequest.displayName = 'proto.graphsearch.TrustedValidationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.TrustedValidationReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.graphsearch.TrustedValidationReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.TrustedValidationReply.displayName = 'proto.graphsearch.TrustedValidationReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.TrustedValidationBulkRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.graphsearch.TrustedValidationBulkRequest.repeatedFields_, null);
};
goog.inherits(proto.graphsearch.TrustedValidationBulkRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.TrustedValidationBulkRequest.displayName = 'proto.graphsearch.TrustedValidationBulkRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.TrustedValidationBulkReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.graphsearch.TrustedValidationBulkReply.repeatedFields_, null);
};
goog.inherits(proto.graphsearch.TrustedValidationBulkReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.TrustedValidationBulkReply.displayName = 'proto.graphsearch.TrustedValidationBulkReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.OutputOracleRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.graphsearch.OutputOracleRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.OutputOracleRequest.displayName = 'proto.graphsearch.OutputOracleRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.OutputOracleReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.graphsearch.OutputOracleReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.OutputOracleReply.displayName = 'proto.graphsearch.OutputOracleReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.StatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.graphsearch.StatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.StatusRequest.displayName = 'proto.graphsearch.StatusRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.graphsearch.StatusReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.graphsearch.StatusReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.graphsearch.StatusReply.displayName = 'proto.graphsearch.StatusReply';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.graphsearch.GraphSearchRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.GraphSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.GraphSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.GraphSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.GraphSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    excludeTxidsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.GraphSearchRequest}
 */
proto.graphsearch.GraphSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.GraphSearchRequest;
  return proto.graphsearch.GraphSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.GraphSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.GraphSearchRequest}
 */
proto.graphsearch.GraphSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludeTxids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.GraphSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.GraphSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.GraphSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.GraphSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExcludeTxidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string txid = 1;
 * @return {string}
 */
proto.graphsearch.GraphSearchRequest.prototype.getTxid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.graphsearch.GraphSearchRequest} returns this
 */
proto.graphsearch.GraphSearchRequest.prototype.setTxid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string exclude_txids = 2;
 * @return {!Array<string>}
 */
proto.graphsearch.GraphSearchRequest.prototype.getExcludeTxidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.graphsearch.GraphSearchRequest} returns this
 */
proto.graphsearch.GraphSearchRequest.prototype.setExcludeTxidsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.graphsearch.GraphSearchRequest} returns this
 */
proto.graphsearch.GraphSearchRequest.prototype.addExcludeTxids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.graphsearch.GraphSearchRequest} returns this
 */
proto.graphsearch.GraphSearchRequest.prototype.clearExcludeTxidsList = function() {
  return this.setExcludeTxidsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.graphsearch.GraphSearchReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.GraphSearchReply.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.GraphSearchReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.GraphSearchReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.GraphSearchReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    txdataList: msg.getTxdataList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.GraphSearchReply}
 */
proto.graphsearch.GraphSearchReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.GraphSearchReply;
  return proto.graphsearch.GraphSearchReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.GraphSearchReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.GraphSearchReply}
 */
proto.graphsearch.GraphSearchReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addTxdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.GraphSearchReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.GraphSearchReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.GraphSearchReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.GraphSearchReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxdataList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      1,
      f
    );
  }
};


/**
 * repeated bytes txdata = 1;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.graphsearch.GraphSearchReply.prototype.getTxdataList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * repeated bytes txdata = 1;
 * This is a type-conversion wrapper around `getTxdataList()`
 * @return {!Array<string>}
 */
proto.graphsearch.GraphSearchReply.prototype.getTxdataList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getTxdataList()));
};


/**
 * repeated bytes txdata = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTxdataList()`
 * @return {!Array<!Uint8Array>}
 */
proto.graphsearch.GraphSearchReply.prototype.getTxdataList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getTxdataList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.graphsearch.GraphSearchReply} returns this
 */
proto.graphsearch.GraphSearchReply.prototype.setTxdataList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.graphsearch.GraphSearchReply} returns this
 */
proto.graphsearch.GraphSearchReply.prototype.addTxdata = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.graphsearch.GraphSearchReply} returns this
 */
proto.graphsearch.GraphSearchReply.prototype.clearTxdataList = function() {
  return this.setTxdataList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.TrustedValidationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.TrustedValidationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.TrustedValidationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.TrustedValidationRequest}
 */
proto.graphsearch.TrustedValidationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.TrustedValidationRequest;
  return proto.graphsearch.TrustedValidationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.TrustedValidationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.TrustedValidationRequest}
 */
proto.graphsearch.TrustedValidationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.TrustedValidationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.TrustedValidationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.TrustedValidationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string txid = 1;
 * @return {string}
 */
proto.graphsearch.TrustedValidationRequest.prototype.getTxid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.graphsearch.TrustedValidationRequest} returns this
 */
proto.graphsearch.TrustedValidationRequest.prototype.setTxid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.TrustedValidationReply.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.TrustedValidationReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.TrustedValidationReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    valid: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.TrustedValidationReply}
 */
proto.graphsearch.TrustedValidationReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.TrustedValidationReply;
  return proto.graphsearch.TrustedValidationReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.TrustedValidationReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.TrustedValidationReply}
 */
proto.graphsearch.TrustedValidationReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setValid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.TrustedValidationReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.TrustedValidationReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.TrustedValidationReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValid();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool valid = 1;
 * @return {boolean}
 */
proto.graphsearch.TrustedValidationReply.prototype.getValid = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.graphsearch.TrustedValidationReply} returns this
 */
proto.graphsearch.TrustedValidationReply.prototype.setValid = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.graphsearch.TrustedValidationBulkRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.TrustedValidationBulkRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.TrustedValidationBulkRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.TrustedValidationBulkRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationBulkRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txidsList: jspb.Message.toObjectList(msg.getTxidsList(),
    proto.graphsearch.TrustedValidationRequest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.TrustedValidationBulkRequest}
 */
proto.graphsearch.TrustedValidationBulkRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.TrustedValidationBulkRequest;
  return proto.graphsearch.TrustedValidationBulkRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.TrustedValidationBulkRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.TrustedValidationBulkRequest}
 */
proto.graphsearch.TrustedValidationBulkRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.graphsearch.TrustedValidationRequest;
      reader.readMessage(value,proto.graphsearch.TrustedValidationRequest.deserializeBinaryFromReader);
      msg.addTxids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.TrustedValidationBulkRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.TrustedValidationBulkRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.TrustedValidationBulkRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationBulkRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.graphsearch.TrustedValidationRequest.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TrustedValidationRequest txids = 1;
 * @return {!Array<!proto.graphsearch.TrustedValidationRequest>}
 */
proto.graphsearch.TrustedValidationBulkRequest.prototype.getTxidsList = function() {
  return /** @type{!Array<!proto.graphsearch.TrustedValidationRequest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.graphsearch.TrustedValidationRequest, 1));
};


/**
 * @param {!Array<!proto.graphsearch.TrustedValidationRequest>} value
 * @return {!proto.graphsearch.TrustedValidationBulkRequest} returns this
*/
proto.graphsearch.TrustedValidationBulkRequest.prototype.setTxidsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.graphsearch.TrustedValidationRequest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.graphsearch.TrustedValidationRequest}
 */
proto.graphsearch.TrustedValidationBulkRequest.prototype.addTxids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.graphsearch.TrustedValidationRequest, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.graphsearch.TrustedValidationBulkRequest} returns this
 */
proto.graphsearch.TrustedValidationBulkRequest.prototype.clearTxidsList = function() {
  return this.setTxidsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.graphsearch.TrustedValidationBulkReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.TrustedValidationBulkReply.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.TrustedValidationBulkReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.TrustedValidationBulkReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationBulkReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    validList: jspb.Message.toObjectList(msg.getValidList(),
    proto.graphsearch.TrustedValidationReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.TrustedValidationBulkReply}
 */
proto.graphsearch.TrustedValidationBulkReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.TrustedValidationBulkReply;
  return proto.graphsearch.TrustedValidationBulkReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.TrustedValidationBulkReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.TrustedValidationBulkReply}
 */
proto.graphsearch.TrustedValidationBulkReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.graphsearch.TrustedValidationReply;
      reader.readMessage(value,proto.graphsearch.TrustedValidationReply.deserializeBinaryFromReader);
      msg.addValid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.TrustedValidationBulkReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.TrustedValidationBulkReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.TrustedValidationBulkReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.TrustedValidationBulkReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.graphsearch.TrustedValidationReply.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TrustedValidationReply valid = 1;
 * @return {!Array<!proto.graphsearch.TrustedValidationReply>}
 */
proto.graphsearch.TrustedValidationBulkReply.prototype.getValidList = function() {
  return /** @type{!Array<!proto.graphsearch.TrustedValidationReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.graphsearch.TrustedValidationReply, 1));
};


/**
 * @param {!Array<!proto.graphsearch.TrustedValidationReply>} value
 * @return {!proto.graphsearch.TrustedValidationBulkReply} returns this
*/
proto.graphsearch.TrustedValidationBulkReply.prototype.setValidList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.graphsearch.TrustedValidationReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.graphsearch.TrustedValidationReply}
 */
proto.graphsearch.TrustedValidationBulkReply.prototype.addValid = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.graphsearch.TrustedValidationReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.graphsearch.TrustedValidationBulkReply} returns this
 */
proto.graphsearch.TrustedValidationBulkReply.prototype.clearValidList = function() {
  return this.setValidList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.OutputOracleRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.OutputOracleRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.OutputOracleRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.OutputOracleRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    vout: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.OutputOracleRequest}
 */
proto.graphsearch.OutputOracleRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.OutputOracleRequest;
  return proto.graphsearch.OutputOracleRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.OutputOracleRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.OutputOracleRequest}
 */
proto.graphsearch.OutputOracleRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.OutputOracleRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.OutputOracleRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.OutputOracleRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVout();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional string txid = 1;
 * @return {string}
 */
proto.graphsearch.OutputOracleRequest.prototype.getTxid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.graphsearch.OutputOracleRequest} returns this
 */
proto.graphsearch.OutputOracleRequest.prototype.setTxid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 vout = 2;
 * @return {number}
 */
proto.graphsearch.OutputOracleRequest.prototype.getVout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.OutputOracleRequest} returns this
 */
proto.graphsearch.OutputOracleRequest.prototype.setVout = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.OutputOracleReply.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.OutputOracleReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.OutputOracleReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.OutputOracleReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    msg: msg.getMsg_asB64(),
    sig: msg.getSig_asB64(),
    tx: msg.getTx_asB64(),
    vout: jspb.Message.getFieldWithDefault(msg, 4, 0),
    tokenid: msg.getTokenid_asB64(),
    tokentype: jspb.Message.getFieldWithDefault(msg, 6, 0),
    value: jspb.Message.getFieldWithDefault(msg, 7, 0),
    isBaton: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    groupid: msg.getGroupid_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.OutputOracleReply}
 */
proto.graphsearch.OutputOracleReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.OutputOracleReply;
  return proto.graphsearch.OutputOracleReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.OutputOracleReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.OutputOracleReply}
 */
proto.graphsearch.OutputOracleReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMsg(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSig(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTx(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVout(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTokenid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTokentype(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setValue(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsBaton(value);
      break;
    case 9:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setGroupid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.OutputOracleReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.OutputOracleReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.OutputOracleReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsg_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSig_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTx_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getVout();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getTokenid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getTokentype();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getIsBaton();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getGroupid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      9,
      f
    );
  }
};


/**
 * optional bytes msg = 1;
 * @return {!(string|Uint8Array)}
 */
proto.graphsearch.OutputOracleReply.prototype.getMsg = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes msg = 1;
 * This is a type-conversion wrapper around `getMsg()`
 * @return {string}
 */
proto.graphsearch.OutputOracleReply.prototype.getMsg_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMsg()));
};


/**
 * optional bytes msg = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMsg()`
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleReply.prototype.getMsg_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMsg()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setMsg = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes sig = 2;
 * @return {!(string|Uint8Array)}
 */
proto.graphsearch.OutputOracleReply.prototype.getSig = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes sig = 2;
 * This is a type-conversion wrapper around `getSig()`
 * @return {string}
 */
proto.graphsearch.OutputOracleReply.prototype.getSig_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSig()));
};


/**
 * optional bytes sig = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSig()`
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleReply.prototype.getSig_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSig()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setSig = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional bytes tx = 3;
 * @return {!(string|Uint8Array)}
 */
proto.graphsearch.OutputOracleReply.prototype.getTx = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes tx = 3;
 * This is a type-conversion wrapper around `getTx()`
 * @return {string}
 */
proto.graphsearch.OutputOracleReply.prototype.getTx_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTx()));
};


/**
 * optional bytes tx = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTx()`
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleReply.prototype.getTx_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTx()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setTx = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional uint32 vout = 4;
 * @return {number}
 */
proto.graphsearch.OutputOracleReply.prototype.getVout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setVout = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes tokenid = 5;
 * @return {!(string|Uint8Array)}
 */
proto.graphsearch.OutputOracleReply.prototype.getTokenid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes tokenid = 5;
 * This is a type-conversion wrapper around `getTokenid()`
 * @return {string}
 */
proto.graphsearch.OutputOracleReply.prototype.getTokenid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTokenid()));
};


/**
 * optional bytes tokenid = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTokenid()`
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleReply.prototype.getTokenid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTokenid()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setTokenid = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional uint32 tokentype = 6;
 * @return {number}
 */
proto.graphsearch.OutputOracleReply.prototype.getTokentype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setTokentype = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 value = 7;
 * @return {number}
 */
proto.graphsearch.OutputOracleReply.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional bool is_baton = 8;
 * @return {boolean}
 */
proto.graphsearch.OutputOracleReply.prototype.getIsBaton = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setIsBaton = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bytes groupid = 9;
 * @return {!(string|Uint8Array)}
 */
proto.graphsearch.OutputOracleReply.prototype.getGroupid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * optional bytes groupid = 9;
 * This is a type-conversion wrapper around `getGroupid()`
 * @return {string}
 */
proto.graphsearch.OutputOracleReply.prototype.getGroupid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getGroupid()));
};


/**
 * optional bytes groupid = 9;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getGroupid()`
 * @return {!Uint8Array}
 */
proto.graphsearch.OutputOracleReply.prototype.getGroupid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getGroupid()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.graphsearch.OutputOracleReply} returns this
 */
proto.graphsearch.OutputOracleReply.prototype.setGroupid = function(value) {
  return jspb.Message.setProto3BytesField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.StatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.StatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.StatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.StatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.StatusRequest}
 */
proto.graphsearch.StatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.StatusRequest;
  return proto.graphsearch.StatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.StatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.StatusRequest}
 */
proto.graphsearch.StatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.StatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.StatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.StatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.StatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.graphsearch.StatusReply.prototype.toObject = function(opt_includeInstance) {
  return proto.graphsearch.StatusReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.graphsearch.StatusReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.StatusReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockHeight: jspb.Message.getFieldWithDefault(msg, 1, 0),
    bestBlockHash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastIncomingZmqTxUnix: jspb.Message.getFieldWithDefault(msg, 3, 0),
    lastOutgoingZmqTxUnix: jspb.Message.getFieldWithDefault(msg, 4, 0),
    lastIncomingZmqTx: jspb.Message.getFieldWithDefault(msg, 5, ""),
    lastOutgoingZmqTx: jspb.Message.getFieldWithDefault(msg, 6, ""),
    lastIncomingZmqBlkUnix: jspb.Message.getFieldWithDefault(msg, 7, 0),
    lastOutgoingZmqBlkUnix: jspb.Message.getFieldWithDefault(msg, 8, 0),
    lastIncomingZmqBlkSize: jspb.Message.getFieldWithDefault(msg, 9, 0),
    lastOutgoingZmqBlkSize: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.graphsearch.StatusReply}
 */
proto.graphsearch.StatusReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.graphsearch.StatusReply;
  return proto.graphsearch.StatusReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.graphsearch.StatusReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.graphsearch.StatusReply}
 */
proto.graphsearch.StatusReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockHeight(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBestBlockHash(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastIncomingZmqTxUnix(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastOutgoingZmqTxUnix(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastIncomingZmqTx(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastOutgoingZmqTx(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastIncomingZmqBlkUnix(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastOutgoingZmqBlkUnix(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastIncomingZmqBlkSize(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastOutgoingZmqBlkSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.graphsearch.StatusReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.graphsearch.StatusReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.graphsearch.StatusReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.graphsearch.StatusReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBlockHeight();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getBestBlockHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastIncomingZmqTxUnix();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getLastOutgoingZmqTxUnix();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getLastIncomingZmqTx();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLastOutgoingZmqTx();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLastIncomingZmqBlkUnix();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getLastOutgoingZmqBlkUnix();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getLastIncomingZmqBlkSize();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getLastOutgoingZmqBlkSize();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
};


/**
 * optional uint32 block_height = 1;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getBlockHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setBlockHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string best_block_hash = 2;
 * @return {string}
 */
proto.graphsearch.StatusReply.prototype.getBestBlockHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setBestBlockHash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint64 last_incoming_zmq_tx_unix = 3;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getLastIncomingZmqTxUnix = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastIncomingZmqTxUnix = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 last_outgoing_zmq_tx_unix = 4;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getLastOutgoingZmqTxUnix = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastOutgoingZmqTxUnix = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string last_incoming_zmq_tx = 5;
 * @return {string}
 */
proto.graphsearch.StatusReply.prototype.getLastIncomingZmqTx = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastIncomingZmqTx = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string last_outgoing_zmq_tx = 6;
 * @return {string}
 */
proto.graphsearch.StatusReply.prototype.getLastOutgoingZmqTx = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastOutgoingZmqTx = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional uint64 last_incoming_zmq_blk_unix = 7;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getLastIncomingZmqBlkUnix = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastIncomingZmqBlkUnix = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint64 last_outgoing_zmq_blk_unix = 8;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getLastOutgoingZmqBlkUnix = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastOutgoingZmqBlkUnix = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint64 last_incoming_zmq_blk_size = 9;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getLastIncomingZmqBlkSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastIncomingZmqBlkSize = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint64 last_outgoing_zmq_blk_size = 10;
 * @return {number}
 */
proto.graphsearch.StatusReply.prototype.getLastOutgoingZmqBlkSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.graphsearch.StatusReply} returns this
 */
proto.graphsearch.StatusReply.prototype.setLastOutgoingZmqBlkSize = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


goog.object.extend(exports, proto.graphsearch);
